openBIMdisk/apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2023 - iLab HKU
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

openBIMdisk/apps/home/routes.py
from apps.home import blueprint
from jinja2 import TemplateNotFound
import sqlite3
import os
from flask import  render_template, redirect, request, url_for, session, send_from_directory, g, flash, jsonify
from flask_login import (
    current_user,
    login_required,
)
from werkzeug.utils import secure_filename
import argparse
from apps.tSdt.IfcSdt import *
from apps.tSdt.io import *
# from apps.tSdt.third_party import json2ifc
# from flask_bootstrap import Bootstrap
import time
from hfc.fabric import Client
import sys,asyncio
from apps import config
# from pyecharts.charts import Bar, Timeline
import json

basedir = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
database_dir = os.path.join(basedir, 'db.sqlite3')
allowed_extension = config.Config.ALLOWED_EXTENSIONS
upload_folder = config.Config.UPLOAD_FOLDER
output_diff = config.Config.OUTPUT_FOLDER_DIFF
output_restore = config.Config.OUTPUT_FOLDER_RESTORE
log_folder = config.Config.LOG_FOLDER
sqlDB =config.Config.SQLALCHEMY_DATABASE_URI.replace('sqlite:///', '')
fabric_folder = config.Config.FABRIC_FOLDER
project = "WCH"

def allowed_file_type(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in allowed_extension

def file_exists(filename):
    return os.path.exists(os.path.join(upload_folder, filename))

@blueprint.route('/index')
@login_required
def index():
    conn = sqlite3.connect(database_dir)
    cursor = conn.cursor()
    currentUser = current_user.username
    cursor.execute("SELECT username, role, orgName FROM Users where username != '" + currentUser + "'")
    userList = cursor.fetchall()
    conn.close()
    return render_template('home/index.html', segment='index', userList=userList)


@blueprint.route('/<template>')
@login_required
def route_template(template):

    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500

# Helper - Extract current page name from request
def get_segment(request):

    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment

    except:
        return None
    
    # function route

@blueprint.route('/to_tsdt', methods=['POST','GET'])
@login_required
def to_tsdt():
    if request.method == 'GET':
        return redirect(url_for('home_blueprint.uploaded_file'))

@blueprint.route('/file', methods=['POST'])
@login_required
def file():
    if request.method == 'POST':
        to_upload_files = request.files.getlist("file")
        for file in to_upload_files:
            if file and allowed_file_type(file.filename) and not file_exists(file.filename):
                filename = secure_filename(file.filename)
                upload_path = os.path.join(upload_folder, filename).replace('\\','/')
                file.save(upload_path)
            elif file and allowed_file_type(file.filename):
                flash('File with the same name already exists')
    return jsonify({'fileNames': file.filename})

@blueprint.route('/uploaded_file', methods=['GET','POST']) 
def uploaded_file():
    logFolders= []
    for dirname in os.listdir(os.path.join(log_folder, "WCH")):
        logFolders.append(dirname)
    return render_template('home/tSDT_computing.html', logFolders=logFolders)

@blueprint.route('/download/<filename>', methods=['GET'])
def download(filename):
    if request.method == 'GET':
        path = os.path.isfile(os.path.join(upload_folder,filename))
        if path:
            return send_from_directory(upload_folder, filename, as_attachment=True)


@blueprint.route('/tsdt_function', methods = ['POST'])
def tsdt_function():
    if request.method == 'POST':
        data = request.json
        files = data.get('fileNames', [])
        fileName1 = files[0]
        fileName2 = files[1]
        file_pth_1 = os.path.join(upload_folder,fileName1)
        file_pth_2 = os.path.join(upload_folder,fileName2)
        result_filePath, result_changeData, module_data = my_sdt_route(file_pth_1, file_pth_2, project)
        # upload to blockchain network
        user_name = "org1.example.com"
        user_authority = "Admin"
        channel_name = "bscchannel"
        tx_id = "WCH" + fileName1.split('.')[0] + '-' + fileName2.split('.')[0]
        activity = 'sdt'
        if 'v' in fileName1 and 'v' in fileName2:
            baseversion = 'V' + fileName1.split('.')[0].split('v')[1]
            targetversion = 'V' + fileName2.split('.')[0].split('v')[1]
        else:
            baseversion = 'V' + fileName1.split('.')[0]
            targetversion = 'V' + fileName2.split('.')[0]
        filePath = result_filePath
        result_fileName = os.path.basename(filePath)
        trans_time = time.ctime(os.path.getctime(filePath))
        fileType = 'sdt_file'
        fileSize = str(round(float(os.path.getsize(filePath)),2)) + 'KB'
        args = [tx_id,activity,baseversion,targetversion,filePath,fileType,fileSize]
        database = getattr(g, 'db', None)
        if database is None:
            database = g.db = sqlite3.connect(sqlDB)
        transID = invoke_transaction(user_name, user_authority, channel_name, args)
        result_changeDetail = result_changeData
        for i in range(0,len(result_changeDetail)):
            item = result_changeDetail[i]
            for key in item:
                component_type = key
                if "Rel" in key or "OwnerHistory" in key or "Property" in key:
                    isRVTobj = 0
                else:
                    isRVTobj = 1
                guid_ll = len(item[key]) # length of 
                for i in range (0,guid_ll):
                    item_data = item[key][i].replace("(","").replace(")","").split(",")
                    guid = item_data[0]
                    changeType = item_data[1]
                    file_ver = item_data[2]
                    ifcID = item_data[3]
                    if changeType != "modify":
                        isTarget = 1
                        isBase = 0
                    elif file_ver == "baseVer":
                        isBase = 1
                        isTarget = 0
                    elif file_ver == "targetVer":
                        isBase = 0
                        isTarget = 1
                    elif file_ver == "baseVer-targetVer":
                        isBase = 1
                        isTarget = 1
                    cursor = database.cursor()
                    cursor.execute("INSERT OR REPLACE INTO bsc_info (transID, GUID, ifcID, ifcType, isRVTobj, changeType, isBase, isTarget) values (?,?,?,?,?,?,?,?)", (transID, guid, ifcID, component_type, isRVTobj, changeType, isBase, isTarget ))
                    database.commit()
        
        for j in range(0,len(module_data)):
            item = module_data[j]
            for key in item:
                module_guid = key
                module_item_data = item[key].replace("(", "").replace(")", "").split(";")
                module_name = module_item_data[0]
                related_obj_guid = module_item_data[2]
                group_level = module_item_data[3]
                related_rel_guid = module_item_data[4]
                cursor = database.cursor()
                cursor.execute("INSERT OR REPLACE INTO module (moduleID, GUID, relatedObj, level, relatedRel) values (?,?,?,?,?)", (module_name, module_guid, related_obj_guid, group_level, related_rel_guid))
                database.commit
        # Upload result to the local sqlite3 database
        cursor = database.cursor()
        cursor.execute("INSERT OR REPLACE INTO blockchainTrans (baseVersion, targetVersion,transID,tsdtName,transTime) values (?,?,?,?,?)", (baseversion, targetversion,transID, result_fileName, trans_time))
        database.commit()
        database.close()
    return redirect(url_for('home_blueprint.computeResult', filename=result_fileName))

def my_sdt_route(file1,file2, projName):
    parser = argparse.ArgumentParser(description='Compute SDT of two IFC SPF files (as JSON).')
    #parser = reqparse.RequestParser()
    parser.add_argument('-a', '--ifc1', type=str, help='input ifc file path #A')
    parser.add_argument('-b', '--ifc2', type=str, help='input ifc file path #B')
    parser.add_argument('-o', '--output', type=str, help='output json file path')
    parser.add_argument('-v', '--verbose', action='store_true', help='logging verbose details to log_folder')
    args,unknown = parser.parse_known_args()
    args.ifc1 = file1
    args.ifc2 = file2
    args.output = output_diff + projName + '/'
    if not os.path.exists(args.output):
        os.makedirs(args.output)
    # generate the log file name accordingly
    if "v" in file1 and "v" in file2:
        subfile1 = file1.split("v")[1].split(".")[0]
        subfile2 = file2.split("v")[1].split(".")[0]
        filename = 'v' + subfile1 + '-v' + subfile2 + '.sdt'
    else:
        filename = 'v' + file1[-5:-4] + '-v' + file2[-5:-4] + '.sdt' 
    IfcSdt.log_folder = LOG_FOLDER_PROJ(file1, file2, projName) + "/"
    args.verbose = 'verbose'
    sdt = IfcSdt()
    sdt.Verbose = args.verbose
    ifc1, idDict1, groupObj1 = sdt.remove_minor_dup(args.ifc1)
    ifc2, idDict2, groupObj2 = sdt.remove_minor_dup(args.ifc2)
    result = sdt.compute_diff(ifc1,ifc2)
    # upload the detailed difference to the database and blockchain 
    changed_item_type_list =[]
    changed_item = []
    group = []
    group_item = []
    for key in result["data_type"]:
        changed_type = key
        guid_list = []
        changed_item_type_list.append(key)
        diff_item = result["data_type"][key]

openBIMdisk/apps/templates/home/blockchain.html
{% extends "layouts/base.html" %}

{% block title %} Blockchain {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<link href="{{ config.ASSETS_ROOT }}/css/button.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}

    <!-- ============================================================== -->
    <!-- Login box.scss -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row align-items-center">
            <div class="col-md-6 col-8 align-self-center">
                <h3 class="page-title mb-0 p-0">BIM Blockchain Monitor</h3>
                <div class="d-flex align-items-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{url_for('home_blueprint.index')}}">Home</a></li>
                            <!-- <li class="breadcrumb-item active" aria-current="page">Timeline</li> -->
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="col-md-6 col-4 align-self-center">
                <div class="text-end upgrade-btn">
                    <a href="https://appseed.us/support/"
                       class="btn btn-danger d-none d-md-inline-block text-white" target="_blank">
                       Support        
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <!-- column -->
            <div class="col-sm-12">
                <a href="http://172.28.183.190:8080/">Blockchain Explorer</a>
                <!-- <iframe src="http://172.28.183.190:8080/" width="800" height="600" frameborder="0"></iframe> -->
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>

{% endblock content %}

{% block javascripts %}

    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
        $(".preloader").fadeOut();
    </script>

{% endblock javascripts %}

openBIMdisk/apps/templates/home/diff_result.html
{% extends "layouts/base.html" %}

{% block title %} diff result {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<link href="{{ config.ASSETS_ROOT }}/css/button.css" rel="stylesheet">
<link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />

{% endblock stylesheets %}

{% block content %}

        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row align-items-center">
                <div class="col-md-6 col-8 align-self-center">
                    <h3 class="page-title mb-0 p-0">tSDT</h3>
                    <div class="d-flex align-items-center">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{url_for('home_blueprint.index')}}">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">tSDT Computing</li>
                            </ol>
                        </nav>
                    </div>
                </div>
                <div class="col-md-6 col-4">
                    <div class="text-end upgrade-btn">
                        <a href="https://appseed.us/support/"
                            class="btn btn-danger d-none d-md-inline-block text-white" target="_blank">
                            Support        
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <!-- Row -->
            <div class="row">
                <!-- Column -->
                <div class="col-lg-6 col-xlg-3 col-md-5">
                    <!-- define the label for the file selection button -->
                    <form action="/file" id="myDropzone" class="dropzone" method="POST">
                        <img src="{{ config.ASSETS_ROOT }}/images/fileUpload.png" style="position: relative; left:37.5%; top:10%;">
                        <div class="fallback">
                            <input type="file" class="custom-file-input" id="fileSelect" name="file" multiple="multiple" style="display: none"> 
                        </div>                                                                                                   
                        <h2 style="text-align: center;">Compute Semantic Differences of Two IFC files</h2>  
                    </form>
                </div>  

                <div class="col-lg-6 col-xlg-3 col-md-5">
                    <!-- define the label for the file selection button -->
                    <div class="rectangle-box">
                        <div class="img">
                            <img src="{{ config.ASSETS_ROOT }}/images/fileDownload.png" style="position: relative; left:37.5%; top:10%;">
                        </div>
                        <!-- <div class="button_card__text">
                            <input type="text" size= "40" id="ifc_file1" name="ifc_file1" class="button_card_input"><br>
                        </div> -->
                        <div class="download">
                            <button type="button" id="downloadButton" style="display: none;" onclick="downloadFile()"></button>
                            <label for="downloadButton" style=" display:flex; background-color: rgb(58, 188, 235); justify-content: center;" class="btn btn-primary mt-5">{{ result }}</label>
                        </div>
                        
                    </div>           
                </div> 
            </div>

            <div class="row">
                <div class="col-lg-6 col-xlg-3 col-md-5">
                    <div id="logfolderId" d="{{logFolders}}" style="display:none"></div>
                    <div class="rectangle-box">
                        <div class="img">
                            <img src="{{ config.ASSETS_ROOT }}/images/querying.png" style="position: relative; left:43%; top:10%;">
                        </div>
                        <br>
                        <div class="restore">
                            <form method="post" onsubmit="return handleSubmit()">
                                <div class="flex-container" id="inputBox" >
                                    <lable for="targetVersion">Base Version</lable>
                                    <input type="text" size= "20" id="baseVersion" name="baseVersion">
                                </div>
                                <br>
                                <div class="flex-container" id="inputBox" >
                                    <lable for="targetVersion">Target Version</lable>
                                    <input type="text" size= "20" id="targetVersion" name="targetVersion">
                                </div>
                                <button type="submit" style="display:none" id="tracing_button"></button>
                            </form>
                            <label for="tracing_button" style=" display:flex; background-color: rgb(58, 188, 235); opacity: 0.7;justify-content: center;" class="btn btn-primary mt-2">Restore</label>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6 col-xlg-3 col-md-5">
                    <!-- define the label for the file selection button -->
                    <div class="rectangle-box">
                        <div class="img">
                            <img src="{{ config.ASSETS_ROOT }}/images/fileDownload.png" style="position: relative; left:37.5%; top:10%;">
                        </div>
                        <div class="download">
                            <button type="button" id="restoreDownload" style="display: none;" onclick="downloadRestoreFile()"></button>
                            <label for="restoreDownload" style=" display:flex; background-color: rgb(58, 188, 235); justify-content: center;" class="btn btn-primary mt-5">Download Restore Result</label>
                        </div>
                    </div>           
                </div> 
            </div>
            <!-- Row -->
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->
            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->

{% endblock content %}

{% block javascripts %}

<script type="text/javascript" src="{{ config.ASSETS_ROOT }}/js/dropzone.js"></script>
<script type="text/javascript" src="{{ config.ASSETS_ROOT }}/js/jquery-3.7.1.js"></script>

<script>
    Dropzone.options.myDropzone = {
    init: function() {
        this.on("complete", function() {
            if(this.getQueuedFiles().length === 0 && this.getUploadingFiles().length === 0){
                var fileNames = []
                this.files.forEach(function(file){
                    fileNames.push(file.name)
                });
                sendFileNames(fileNames)
            }
        });
      }
    };

    function sendFileNames(fileNames){
        fetch('/tsdt_function', {
            method: 'POST',
            headers: {
            'Content-Type': 'application/json',
            },
            body: JSON.stringify({ fileNames: fileNames }),
        })
        .then(response => response.json())
        .then(data => {
            console.log(data);
            downloadResult(data);
        })
        .catch(error => {
            console.error('Error:', error);
        });
    }

    function downloadFile(){
        resultFile = "{{ result }}";
        var fileUrl = '/diff/WCH/'+resultFile;
        // console.log(fileUrl)
        fetch(fileUrl)
        .then(response => response.blob())
        .then(blob => {
            const a = document.createElement('a');
            a.href = window.URL.createObjectURL(blob);
            document.body.appendChild(a)
            a.click();
            document.body.removeChild(a);
        })
        .catch(error => {
            console.error('Error: ', error);
        });
    }
</script>

<script>
    function handleSubmit() {
        var base_version = document.getElementById('baseVersion').value;
        var target_version = document.getElementById('targetVersion').value;
        var Project = "WCH";
        // determine whether there is the difference record
        var sdt_aim = base_version + "-" + target_version
        var sdt_aim_reverse = target_version + "-" + base_version
        var log_folder_records = document.getElementById('logfolderId').getAttribute('d') // this is a string result
        // Convert the Result from String to a list
        var logFolderList = []
        logFolderList = log_folder_records.replace("[", "").replace("]","").split(",")
        for(k=0;k<=logFolderList.length-1;k++){
            log_item = logFolderList[k].replace("'","").replace("'","").replace(" ","")
            console.log(log_item)
            if(k<logFolderList.length-1 && log_item === sdt_aim){
                var base_version_real = base_version
                var target_version_real = target_version
                break;
            }
            else if (k<logFolderList.length-1 && log_item === sdt_aim_reverse){
                var base_version_real = target_version
                var target_version_real = base_version
                break;
            }
            else if (k<logFolderList.length-1){
                continue
            }
            else if (k === logFolderList.length-1){
                if(log_item === sdt_aim){
                    var base_version_real = base_version
                    var target_version_real = target_version
                    break;
                }
                else if(log_item === sdt_aim_reverse){
                    var base_version_real = target_version
                    var target_version_real = base_version
                    break;
                }
                else{
                    console.log("No tSDT records!")
                    swal({
                        title: "No tSDT Records!",
                        text: "The semantic difference of these two BIM versions has not been computed before, please run tSDT function to capture differences first.",
                        showCancelButton: true
                    })
                } 
            }
        }   
        console.log("The real base version is " + base_version_real)
        console.log("The real target version is " + target_version_real)
        var xhr = new XMLHttpRequest();
        xhr.open('POST', '/tsdt_restore');
        xhr.setRequestHeader('Content-Type', 'application/json'); 
        xhr.onload = function() {
            if(xhr.status === 200){
                window.location.href = '/restore_result'
            }
            console.log(xhr.responseText);
        };
        xhr.send(JSON.stringify({baseVersion: base_version_real, targetVersion: target_version_real, Project: Project}));
        return false;
    }
 </script>

<script>
    function downloadRestoreFile(){
        resultFile = "{{ restoreResult }}";
        var fileUrl = '/restore/WCH/'+resultFile;
        // console.log(fileUrl)
        fetch(fileUrl)
        .then(response => response.blob())
        .then(blob => {
            const a = document.createElement('a');
            a.href = window.URL.createObjectURL(blob);
            document.body.appendChild(a)
            a.click();
            document.body.removeChild(a);
        })
        .catch(error => {
            console.error('Error: ', error);
        });
    }
</script>
{% endblock javascripts %}